### ISSUE TITLE
ir_remote_mqtt.ino

### ISSUE THREAD

**Issue by ozogp** [estevez-dev/edwin-home#1]
Hello,
I have a problem when compiling the program I get an error

ir_remote_mqtt.ino.ino: In function 'void callback(char*, byte*, unsigned int)':
ir_remote_mqtt.ino:81:80: error: 'decode_base64' was not declared in this scope
 unsigned int decodedDataLength = decode_base64(base64Data, decoded8BitArray);
                                                                                ^
exit status 1
'decode_base64' was not declared in this scope

Where did I go wrong? Please help.
Thank you

**Comment by estevez-dev** [comment]
Hi. Are you sure you have `#include <base64.hpp>`? And do you have [base64-arduino](https://github.com/Densaugeo/base64_arduino) library installed? This function is from that library.

**Comment by ozogp** [comment]
Hello, my mistake, I played the wrong library. Thanks for the guidance.

I have a question about the MQTT IR bridge - I uploaded the program to (Wemos) D1 mini connected to (Wemos) D1 mini IR Controller Shield
(Pin D3 sends, pin D4 receives, additionally I turned on all IR1, IR2, IR3, IR4).
Compilation and save correct. I turned on the MQTT.fx application in search of Topics, found state / edwibridge / state in the message states
{"state": "idle", "firmwareVersion": "1.1"} and that's it. I honestly don't know what to do next? I need to read the signal from the remote control, e.g.
Samsung Blu-Ray, air conditioning to be able to control them from Domoticz.
When I direct the remote control towards the board and I switch the key the LED is blinking - no messages MQTT.fx appear. The IR board works for sure because I have another Wemos D1 mini
with ESPEasy and the IR Transmitter module turned on and I can use commands - including turn on / off Samsung TV instead of the remote control.
Regards
Przemyslaw

**Comment by estevez-dev** [comment]
Well, you can open a console in Arduino IDE (if you are using Arduino IDE) to see code reads when [DEBUG](https://github.com/estevez-dev/edwin-home/blob/20a157490f31f11bfca99f6b568b49f3d9301ae5/devices/edwin_mqtt_ir_bridge/edwin_mqtt_ir_bridge.ino#L12) is enabled. Also, the codes should be sent in `state/edwinbridge/state` topic. Try to enable debug and see the console output in Arduino IDE.

**Comment by ozogp** [comment]
17:07:45.469 -> ..ip:10.10.30.42,mask:255.255.255.192,gw:10.10.30.1
17:07:46.451 -> .
17:07:46.451 -> WiFi connected
17:07:46.451 -> IP address: 
17:07:46.451 -> 10.10.30.42
17:07:46.451 -> Attempting MQTT connection...connected
17:07:46.686 -> Publish topic: state/edwinbridge/state
17:07:46.686 -> Publish message: {"state" : "idle", "firmwareVersion": "1.1"}
17:07:46.686 -> Subscribed to:
17:07:46.686 -> com/edwinbridge/ir
17:07:46.686 -> com/edwinbridge/mode
17:07:53.994 -> pm open,type:2 0

**Comment by ozogp** [comment]
Thank you very much for help. I made the change above is the result.
Connected to a local network, MQTT, posted topic state / edwinbridge / state.
I honestly don't know what to do next. I understand that by pressing the key in the remote control, the LED on Wemos is to flash stronger and in MQTT.fx in the topic there are to be codes.

**Comment by estevez-dev** [comment]
Oh, I just realized! By default this bridge will listen for ir data sent through MQTT to send it through IR led. To start listening IR data from your remotes through IR receiver you need to send payload `i` to `com/edwinbridge/mode` topic.

**Comment by ozogp** [comment]
Hi, thanks for the answer.
I understand that I need to send a message via MQTT.x with the value "i". Then it will be possible to read the signal sent from the remote control in the next message via MQTT.x
Unfortunately, I will be able to test it only in a few days.
I really want this to work, it's a great project and will be of great help to me in home automation.
Regards
Przemyslaw

**Comment by ozogp** [comment]
Hi,
everything works fine. I can control several devices with the IR transmitter - ESP Easy - Domoticz. 
Unfortunately, on the device (air conditioning) I wanted to read "dataType" and "date" the most. Shows the value "UNKNOWN" which unfortunately as a type is not supported by the IR transmitter in ESP Easy. It's hard.
However, thanks for your help, great software, great idea.
regards
Przemyslaw

**Comment by estevez-dev** [comment]
Glad to be helpful
